# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: hexo
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: 12.x
      - name: Setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "1172426418@qq.com"
          git config --global user.name "1172426418"
          npm install hexo-cli -g
          npm i hexo-theme-ayer -S -g
          npm install --save hexo-blog-encrypt -g
          npm install hexo-generator-searchdb --save -g
          npm install hexo-generator-feed --save -g
          npm install --save hexo-deployer-git -g
          npm install
      - name: Hexo deploy
        run: |
          hexo clean
          hexo d
      - name: Build and Deploy
        uses: y4code/hexo-deploy-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY_KEY }}
          PUBLISH_REPOSITORY: 1172426418/1172426418.github.io # The repository the action should deploy to.
          BRANCH: master  # The branch the action should deploy to.
          PUBLISH_DIR: ./public # The folder the action should deploy.